#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, you may
#       specify it by setting the SHELL variable when running this script.
#
#   (2) Uncomment those lines in addition to JAVA_OPTS when necessary:
#
##############################################################################

app_path=$( cd "${app_path%/*}" && pwd -P ) && app_path="$app_path/$(basename -- "$0")"
APP_HOME=$( cd "${APP_HOME:-/opt/gradle}" && pwd -P ) || exit

if [ ! -r "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ] ; then
    echo "Error: Gradle wrapper not found."
    echo "Please run: gradle wrapper"
    exit 1
fi

DEFAULT_JVM_OPTS=' -Xmx64m -Xms64m'

JVM_OPTS=$(echo "$DEFAULT_JVM_OPTS" | tr '\n' ' ')

exec "$JAVACMD" $JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"